#!/bin/bash
echo "Введите ip и порт, который вы хотите проверить"
read ipp
case $ipp in
*.*.*.*\ *)
timeout 5 telnet $ipp 1> /var/log/syslog 2> /dev/null 
if [[ -s /var/log/syslog ]]; then
echo "Ресурс доступен"
else
echo "Возникла непредвиденная ошибка"
fi;
;;
*)
echo "Введите корректрый адрес, например 8.8.8.8 23"
;;
esac
