#!/bin/bash
echo "Какую дирректорию вы хотите проверить?"
read dir
if [[ -e $dir ]]; then
echo "Этот каталог существует"
elif [[ ! -e $dir ]]; then
echo "Такой дирректории нет, создаю..."
mkdir $dir
echo "Дирректория создана"
fi;
