#!/bin/bash
# скрипт на проверку расширения файла
echo "Введите полное имя файла (с расширением)"
read filename
case $filename in
*.jpg | *.gif | *.png)
    	echo "Это image файл"
;;
*.wav | *.mp3)
    	echo "Это audio файл"
;;
*.txt | *.doc)
    	echo "Это text файл"
;;
*)
    	echo "Unknown"
;;
esac
